services:

  active-server:
    container_name: "${TAG_ORG}"
    build:
      context: "../${BUILD_DIR}"
      dockerfile: "../docker/dockerfile-activemq"
      no_cache: true
      args:
        ACTIVEMQ_DOCKER_GITUSER: "${ACTIVEMQ_DOCKER_GIT_USER}"
        ACTIVEMQ_DOCKER_GITSERVER: "${ACTIVEMQ_DOCKER_GIT_SERVER}"
        ACTIVEMQ_DOCKER_GITCLIENT: "${ACTIVEMQ_DOCKER_GIT_CLIENT}"
        ACTIVEMQ_DOCKER_GITCONSUMER: "${ACTIVEMQ_DOCKER_GIT_CONSUMER}"
        ACTIVEMQ_DOCKER_GITPASSWORD: "${ACTIVEMQ_DOCKER_GIT_PASSWORD}"
        ACTIVEMQ_DOCKER_ACTIVEMQSHA512: "${ACTIVEMQ_DOCKER_ACTIVEMQ_SHA512}"
        ACTIVEMQ_DOCKER_ACTIVEMQDOWNLOAD: "${ACTIVEMQ_DOCKER_ACTIVEMQ_DOWNLOAD}"
        ACTIVEMQ_DOCKER_ACTIVEMQPACKAGENAME: "${ACTIVEMQ_DOCKER_ACTIVEMQ_PACKAGENAME}"
        ACTIVEMQ_DOCKER_GRADLEPACKAGENAME: "${ACTIVEMQ_DOCKER_GRADLE_PACKAGENAME}"
        ACTIVEMQ_DOCKER_GRADLEDOWNLOAD: "${ACTIVEMQ_DOCKER_GRADLE_DOWNLOAD}"
        ACTIVEMQ_DOCKER_SERVERHOSTNAME: "${ACTIVEMQ_DOCKER_SERVER_HOSTNAME}"
        ACTIVEMQ_DOCKER_USERNAME: "${ACTIVEMQ_DOCKER_USER_NAME}"
        ACTIVEMQ_DOCKER_USERPASSWORD: "${ACTIVEMQ_DOCKER_USER_PASSWORD}"
    image: "${TAG_PREFIX_ACTIVESERVER}"
    network_mode: "${ACTIVEMQ_DOCKER_NETWORK_TYPE}"
    ports:
      - "22:22/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
      - "8161:8161/tcp"
      - "8443:8443/tcp"
      - "61616:61616/tcp"

